// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtBpbsfSlRpk3r4mXzDO3fi4r9kbJMwjs',
    appId: '1:893362985920:web:66545a707e702163be4625',
    messagingSenderId: '893362985920',
    projectId: 'newapp-48814',
    authDomain: 'newapp-48814.firebaseapp.com',
    storageBucket: 'newapp-48814.firebasestorage.app',
    measurementId: 'G-F3YWN5FHCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOUzuEBwvmKKPIWfwCHeZzn7_dTe_cs-4',
    appId: '1:893362985920:android:6ab3435be96de310be4625',
    messagingSenderId: '893362985920',
    projectId: 'newapp-48814',
    storageBucket: 'newapp-48814.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5avh_e7R93V6_FYPtzVotcQx-2cdeQ7c',
    appId: '1:893362985920:ios:8901e74ff123830ebe4625',
    messagingSenderId: '893362985920',
    projectId: 'newapp-48814',
    storageBucket: 'newapp-48814.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5avh_e7R93V6_FYPtzVotcQx-2cdeQ7c',
    appId: '1:893362985920:ios:8901e74ff123830ebe4625',
    messagingSenderId: '893362985920',
    projectId: 'newapp-48814',
    storageBucket: 'newapp-48814.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtBpbsfSlRpk3r4mXzDO3fi4r9kbJMwjs',
    appId: '1:893362985920:web:7012ce0558dddec4be4625',
    messagingSenderId: '893362985920',
    projectId: 'newapp-48814',
    authDomain: 'newapp-48814.firebaseapp.com',
    storageBucket: 'newapp-48814.firebasestorage.app',
    measurementId: 'G-MVY277VWJ5',
  );

}